In [1]:
import ipyparallel as ipp

# Create an MPI cluster with 8 engines
cluster = ipp.Cluster(engines="mpi", n=4)

# Start and connect to the cluster
rc = cluster.start_and_connect_sync()

# Enable IPython magics for parallel processing
rc[:].activate()

Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

In [2]:
%%px --block
import rockverse as rv
import numpy as np
a=rv.array(np.sort(np.random.rand(10)), chunks=None)

In [3]:
%%px --block
a.zarray[...]

Out[1:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[2:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[3:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[0:2]: 
array([0.00605097, 0.1242743 , 0.2655546 , 0.4552401 , 0.46067488,
       0.49740078, 0.69864817, 0.82079225, 0.87360421, 0.91137548])

In [4]:
%%px --block
a[...]

Out[0:3]: 
array([0.00605097, 0.1242743 , 0.2655546 , 0.4552401 , 0.46067488,
       0.49740078, 0.69864817, 0.82079225, 0.87360421, 0.91137548])

Out[3:3]: 
array([0.00605097, 0.1242743 , 0.2655546 , 0.4552401 , 0.46067488,
       0.49740078, 0.69864817, 0.82079225, 0.87360421, 0.91137548])

Out[2:3]: 
array([0.00605097, 0.1242743 , 0.2655546 , 0.4552401 , 0.46067488,
       0.49740078, 0.69864817, 0.82079225, 0.87360421, 0.91137548])

Out[1:3]: 
array([0.00605097, 0.1242743 , 0.2655546 , 0.4552401 , 0.46067488,
       0.49740078, 0.69864817, 0.82079225, 0.87360421, 0.91137548])

In [5]:
%%px --block
c = rv.core.Coordinate(a)

In [6]:
%%px --block
a.name='rodo'
a.unit='m/s2'
a.latex_unit='$m/s^2$'
a.latex_name=r"$\frac{1}{12}$"
c.get_plot_label(unit=False)


Out[1:5]: ''

Out[0:5]: ''

Out[3:5]: ''

Out[2:5]: ''

In [7]:
%%px --block
c.closest_value(0.32)

Out[1:6]: np.float64(0.26555459904179757)

Out[0:6]: np.float64(0.26555459904179757)

Out[3:6]: np.float64(0.26555459904179757)

Out[2:6]: np.float64(0.26555459904179757)

In [8]:
%%px --block
i = c.closest_index(0.32)
i

Out[2:7]: np.int64(2)

Out[1:7]: np.int64(2)

Out[0:7]: np.int64(2)

Out[3:7]: np.int64(2)

In [9]:
%%px --block
c[i]

Out[2:8]: np.float64(0.26555459904179757)

Out[0:8]: np.float64(0.26555459904179757)

Out[3:8]: np.float64(0.26555459904179757)

Out[1:8]: np.float64(0.26555459904179757)

In [11]:
%%px --block
coords = rv.core.CoordinateSet(
    rv.core.Coordinate(rv.array(np.sort(np.random.rand(10)), chunks=None)),
    rv.core.Coordinate(rv.array(np.sort(np.random.rand(10)), chunks=None)),
    rv.core.Coordinate(rv.array(np.sort(np.random.rand(10)), chunks=None)),)

In [16]:
%%px --block
coords[1].name='sx'
coords[2].unit='ssss'

In [17]:
%%px --block
coords.get_plot_labels()

Out[0:16]: ('', 'sx', 'sx (ssss)')

Out[3:16]: ('', 'sx', 'sx (ssss)')

Out[2:16]: ('', 'sx', 'sx (ssss)')

Out[1:16]: ('', 'sx', 'sx (ssss)')

In [18]:
%%px --block
coords['sx'].attrs


[2:execute]
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1
[3:execute]
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1
[1:execute]
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1
[0:execute]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[17], line 1
----> 1 coords['sx'].attrs

File ~\Downloads\rockverse\src\rockverse\core\coordinates.py:202, in CoordinateSet.__getitem__(self, index)
    200 names = self.names
    201 if len([n for n in names if n == index]) > 1:
--> 202     collective_raise(KeyError(f'Coordinate names must be unique. Got {names}.'))
    203 ind = [k for k, v in enumerate(self.names) if v == index][0]
    204 return self._coordinates[ind]

File ~\Downloads\rockverse\src\rockverse\errors.py:15, in collective_raise(e)
     13 def collective_raise(e):
     14     if mpi_rank 

AlreadyDisplayedError: 4 errors