In [1]:
import ipyparallel as ipp

# Create an MPI cluster with 8 engines
cluster = ipp.Cluster(engines="mpi", n=4)

# Start and connect to the cluster
rc = cluster.start_and_connect_sync()

# Enable IPython magics for parallel processing
rc[:].activate()

Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

In [2]:
%%px --block
import rockverse as rv
import numpy as np
a=rv.coordinate(data=np.sort(np.random.rand(10)))

%px:   0%|          | 0/4 [00:00<?, ?tasks/s]

In [3]:
%%px --block
a.zarray[...]

Out[1:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[2:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[0:2]: 
array([0.00460554, 0.0428783 , 0.0640024 , 0.22696999, 0.23130396,
       0.44324291, 0.61163648, 0.6518838 , 0.69342109, 0.81541353])

Out[3:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
%%px --block
a

Out[0:3]: <rockverse.core.coordinates.Coordinate at 0x245d3baef90>

Out[2:3]: <rockverse.core.coordinates.Coordinate at 0x26406e9fce0>

Out[3:3]: <rockverse.core.coordinates.Coordinate at 0x183c5290260>

Out[1:3]: <rockverse.core.coordinates.Coordinate at 0x17f412ce780>

In [5]:
%%px --block
a.name='rodo'
a.unit='m/s2'
a.latex_unit='$m/s^2$'
a.latex_name=r"$\frac{1}{12}$"
a.get_plot_label(latex=True, unit=True)

Out[0:4]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[3:4]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[1:4]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[2:4]: '$\\frac{1}{12}$ ($m/s^2$)'

In [6]:
%%px --block
a.closest_index(0.32)

Out[3:5]: np.int64(4)

Out[0:5]: np.int64(4)

Out[1:5]: np.int64(4)

Out[2:5]: np.int64(4)

In [7]:
%%px --block
i = a.closest_index(0.32)
i

Out[3:6]: np.int64(4)

Out[0:6]: np.int64(4)

Out[1:6]: np.int64(4)

Out[2:6]: np.int64(4)

In [8]:
%%px --block
a[i]

Out[1:7]: np.float64(0.23130396475236226)

Out[0:7]: np.float64(0.23130396475236226)

Out[2:7]: np.float64(0.23130396475236226)

Out[3:7]: np.float64(0.23130396475236226)

In [9]:
%%px --block
coords = rv.CoordinateSet(
    rv.coordinate(np.sort(np.random.rand(10))),
    rv.coordinate(np.sort(np.random.rand(10))),
    rv.coordinate(np.sort(np.random.rand(10))))

In [10]:
%%px --block
coords[2].name='sx'
coords[2].unit='ssss'

In [11]:
%%px --block
coords['sx']
coords.get_plot_labels()

Out[1:10]: ('', '', 'sx (ssss)')

Out[2:10]: ('', '', 'sx (ssss)')

Out[3:10]: ('', '', 'sx (ssss)')

Out[0:10]: ('', '', 'sx (ssss)')

In [12]:
%%px --block
coords['sx'].attrs


Out[3:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[2:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[0:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[1:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

In [13]:
%%px --block
coords2 = rv.CoordinateSet(coords[0], coords[2])
print([coords[k].zarray for k in range(len(coords))])
print([coords2[k].zarray for k in range(len(coords2))])

coords[0] is coords2[0]

[stdout:2] [<Array memory://2628636299968 shape=(10,) dtype=float64>, <Array memory://2628636300352 shape=(10,) dtype=float64>, <Array memory://2629101870272 shape=(10,) dtype=float64>]
[<Array memory://2628636299968 shape=(10,) dtype=float64>, <Array memory://2629101870272 shape=(10,) dtype=float64>]


[stdout:0] [<Array memory://2498928633344 shape=(10,) dtype=float64>, <Array memory://2498884083136 shape=(10,) dtype=float64>, <Array memory://2498928630528 shape=(10,) dtype=float64>]
[<Array memory://2498928633344 shape=(10,) dtype=float64>, <Array memory://2498928630528 shape=(10,) dtype=float64>]


[stdout:3] [<Array memory://1665546878272 shape=(10,) dtype=float64>, <Array memory://1665080872512 shape=(10,) dtype=float64>, <Array memory://1665545834944 shape=(10,) dtype=float64>]
[<Array memory://1665546878272 shape=(10,) dtype=float64>, <Array memory://1665545834944 shape=(10,) dtype=float64>]


[stdout:1] [<Array memory://1646157881536 shape=(10,) dtype=float64>, <Array memory://1645693556096 shape=(10,) dtype=float64>, <Array memory://1646113403392 shape=(10,) dtype=float64>]
[<Array memory://1646157881536 shape=(10,) dtype=float64>, <Array memory://1646113403392 shape=(10,) dtype=float64>]


Out[2:12]: True

Out[1:12]: True

Out[3:12]: True

Out[0:12]: True

In [14]:
%%px --block
b = rv.array(data=np.sort(np.random.rand(12)), chunks=(3,))
import numpy as np
np.array(b, copy=True)

[stderr:3] C:\Users\GOB7\AppData\Local\Temp\ipykernel_23140\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


[stderr:0] C:\Users\GOB7\AppData\Local\Temp\ipykernel_27504\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


[stderr:2] C:\Users\GOB7\AppData\Local\Temp\ipykernel_19928\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


Out[3:13]: 
array([0.05789409, 0.06358705, 0.25492475, 0.25554013, 0.34644183,
       0.35844354, 0.42590101, 0.43625254, 0.56138535, 0.72555875,
       0.77838358, 0.87760022])

Out[2:13]: 
array([0.05789409, 0.06358705, 0.25492475, 0.25554013, 0.34644183,
       0.35844354, 0.42590101, 0.43625254, 0.56138535, 0.72555875,
       0.77838358, 0.87760022])

Out[0:13]: 
array([0.05789409, 0.06358705, 0.25492475, 0.25554013, 0.34644183,
       0.35844354, 0.42590101, 0.43625254, 0.56138535, 0.72555875,
       0.77838358, 0.87760022])

[stderr:1] C:\Users\GOB7\AppData\Local\Temp\ipykernel_16500\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


Out[1:13]: 
array([0.05789409, 0.06358705, 0.25492475, 0.25554013, 0.34644183,
       0.35844354, 0.42590101, 0.43625254, 0.56138535, 0.72555875,
       0.77838358, 0.87760022])