In [1]:
import ipyparallel as ipp

# Create an MPI cluster with 8 engines
cluster = ipp.Cluster(engines="mpi", n=4)

# Start and connect to the cluster
rc = cluster.start_and_connect_sync()

# Enable IPython magics for parallel processing
rc[:].activate()

Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

In [2]:
%%px --block
import rockverse as rv
import numpy as np
a=rv.coordinate(data=np.sort(np.random.rand(10)))

%px:   0%|          | 0/4 [00:00<?, ?tasks/s]

In [3]:
%%px --block
a.zarray[...]

Out[0:2]: 
array([0.17934232, 0.2422499 , 0.36070475, 0.46693166, 0.50368918,
       0.58470691, 0.63029311, 0.69442795, 0.74275838, 0.90361365])

Out[1:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[3:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[2:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
%%px --block
a

Out[0:3]: <rockverse.core.coordinates.Coordinate at 0x25d4c8d6630>

Out[1:3]: <rockverse.core.coordinates.Coordinate at 0x1f74fe6ba40>

Out[3:3]: <rockverse.core.coordinates.Coordinate at 0x28b62464680>

Out[2:3]: <rockverse.core.coordinates.Coordinate at 0x254ea374380>

In [5]:
%%px --block
a.name='rodo'
a.unit='m/s2'
a.latex_unit='$m/s^2$'
a.latex_name=r"$\frac{1}{12}$"
a.get_plot_label(latex=True, unit=True)

Out[1:4]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[0:4]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[2:4]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[3:4]: '$\\frac{1}{12}$ ($m/s^2$)'

In [6]:
%%px --block
a.closest_index(0.32)

Out[0:5]: np.int64(2)

Out[3:5]: np.int64(2)

Out[2:5]: np.int64(2)

Out[1:5]: np.int64(2)

In [7]:
%%px --block
i = a.closest_index(0.32)
i

Out[0:6]: np.int64(2)

Out[1:6]: np.int64(2)

Out[2:6]: np.int64(2)

Out[3:6]: np.int64(2)

In [8]:
%%px --block
a[i]

Out[0:7]: np.float64(0.36070474817595255)

Out[1:7]: np.float64(0.36070474817595255)

Out[2:7]: np.float64(0.36070474817595255)

Out[3:7]: np.float64(0.36070474817595255)

In [9]:
%%px --block
coords = rv.CoordinateSet(
    rv.coordinate(np.sort(np.random.rand(10))),
    rv.coordinate(np.sort(np.random.rand(10))),
    rv.coordinate(np.sort(np.random.rand(10))))

In [10]:
%%px --block
coords[2].name='sx'
coords[2].unit='ssss'

In [11]:
%%px --block
coords['sx']
coords.get_plot_labels()

Out[3:10]: ('', '', 'sx (ssss)')

Out[2:10]: ('', '', 'sx (ssss)')

Out[1:10]: ('', '', 'sx (ssss)')

Out[0:10]: ('', '', 'sx (ssss)')

In [12]:
%%px --block
coords['sx'].attrs


Out[1:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[2:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[3:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[0:11]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

In [16]:
%%px --block
coords2 = rv.CoordinateSet(coords[0], coords[2])
print([coords[k].zarray for k in range(len(coords))])
print([coords2[k].zarray for k in range(len(coords2))])

coords[0] is coords2[0]

[stdout:2] [<Array memory://2563733046144 shape=(10,) dtype=float64>, <Array memory://2563266891520 shape=(10,) dtype=float64>, <Array memory://2563266851008 shape=(10,) dtype=float64>]
[<Array memory://2563733046144 shape=(10,) dtype=float64>, <Array memory://2563266851008 shape=(10,) dtype=float64>]


[stdout:1] [<Array memory://2161710723776 shape=(10,) dtype=float64>, <Array memory://2161244755520 shape=(10,) dtype=float64>, <Array memory://2161710879808 shape=(10,) dtype=float64>]
[<Array memory://2161710723776 shape=(10,) dtype=float64>, <Array memory://2161710879808 shape=(10,) dtype=float64>]


[stdout:0] [<Array memory://2599829491136 shape=(10,) dtype=float64>, <Array memory://2599830776000 shape=(10,) dtype=float64>, <Array memory://2599792502464 shape=(10,) dtype=float64>]
[<Array memory://2599829491136 shape=(10,) dtype=float64>, <Array memory://2599792502464 shape=(10,) dtype=float64>]


Out[1:14]: True

[stdout:3] [<Array memory://2797245159872 shape=(10,) dtype=float64>, <Array memory://2797235284992 shape=(10,) dtype=float64>, <Array memory://2797711545984 shape=(10,) dtype=float64>]
[<Array memory://2797245159872 shape=(10,) dtype=float64>, <Array memory://2797711545984 shape=(10,) dtype=float64>]


Out[2:14]: True

Out[3:14]: True

Out[0:14]: True

In [ ]:
%%px --block
b = rv.array(data=np.sort(np.random.rand(12)), chunks=(3,))
import numpy as np
np.array(b, copy=True)

[stderr:1] C:\Users\GOB7\AppData\Local\Temp\ipykernel_10108\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


[stderr:3] C:\Users\GOB7\AppData\Local\Temp\ipykernel_12020\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


[stderr:0] C:\Users\GOB7\AppData\Local\Temp\ipykernel_23640\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


Out[1:21]: 
array([0.05343399, 0.18160849, 0.22415594, 0.31708262, 0.35834216,
       0.36805296, 0.58825908, 0.60963073, 0.74024168, 0.77468211,
       0.8360277 , 0.85032072])

[stderr:2] C:\Users\GOB7\AppData\Local\Temp\ipykernel_14540\1160086135.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.array(b, copy=True)


Out[2:21]: 
array([0.05343399, 0.18160849, 0.22415594, 0.31708262, 0.35834216,
       0.36805296, 0.58825908, 0.60963073, 0.74024168, 0.77468211,
       0.8360277 , 0.85032072])

Out[3:21]: 
array([0.05343399, 0.18160849, 0.22415594, 0.31708262, 0.35834216,
       0.36805296, 0.58825908, 0.60963073, 0.74024168, 0.77468211,
       0.8360277 , 0.85032072])

Out[0:21]: 
array([0.05343399, 0.18160849, 0.22415594, 0.31708262, 0.35834216,
       0.36805296, 0.58825908, 0.60963073, 0.74024168, 0.77468211,
       0.8360277 , 0.85032072])