In [1]:
import ipyparallel as ipp

# Create an MPI cluster with 8 engines
cluster = ipp.Cluster(engines="mpi", n=4)

# Start and connect to the cluster
rc = cluster.start_and_connect_sync()

# Enable IPython magics for parallel processing
rc[:].activate()

Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

TimeoutError: 4 engines not ready in 60 seconds. Currently ready: 0

In [2]:
%%px --block
import rockverse as rv
import numpy as np
a=rv.array(np.sort(np.random.rand(10)), chunks=None)

%px:   0%|          | 0/4 [00:00<?, ?tasks/s]

In [3]:
%%px --block
a.zarray[...]

Out[1:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[2:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Out[0:2]: 
array([0.09457692, 0.16931141, 0.41954263, 0.47831271, 0.5120419 ,
       0.58815972, 0.62328464, 0.81479838, 0.91927193, 0.95600976])

Out[3:2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
%%px --block
a[...]

Out[0:3]: 
array([0.09457692, 0.16931141, 0.41954263, 0.47831271, 0.5120419 ,
       0.58815972, 0.62328464, 0.81479838, 0.91927193, 0.95600976])

Out[2:3]: 
array([0.09457692, 0.16931141, 0.41954263, 0.47831271, 0.5120419 ,
       0.58815972, 0.62328464, 0.81479838, 0.91927193, 0.95600976])

Out[1:3]: 
array([0.09457692, 0.16931141, 0.41954263, 0.47831271, 0.5120419 ,
       0.58815972, 0.62328464, 0.81479838, 0.91927193, 0.95600976])

Out[3:3]: 
array([0.09457692, 0.16931141, 0.41954263, 0.47831271, 0.5120419 ,
       0.58815972, 0.62328464, 0.81479838, 0.91927193, 0.95600976])

In [5]:
%%px --block
c = rv.core.Coordinate(a)

In [18]:
%%px --block
a.name='rodo'
a.unit='m/s2'
a.latex_unit='$m/s^2$'
a.latex_name=r"$\frac{1}{12}$"
a.get_plot_label(latex=True, unit=True)

Out[1:17]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[2:17]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[0:17]: '$\\frac{1}{12}$ ($m/s^2$)'

Out[3:17]: '$\\frac{1}{12}$ ($m/s^2$)'

In [7]:
%%px --block
c.closest_index(0.32)

Out[0:6]: np.int64(2)

Out[3:6]: np.int64(2)

Out[1:6]: np.int64(2)

Out[2:6]: np.int64(2)

In [8]:
%%px --block
i = c.closest_index(0.32)
i

Out[1:7]: np.int64(2)

Out[3:7]: np.int64(2)

Out[0:7]: np.int64(2)

Out[2:7]: np.int64(2)

In [9]:
%%px --block
c[i]

Out[1:8]: np.float64(0.4195426327248053)

Out[3:8]: np.float64(0.4195426327248053)

Out[2:8]: np.float64(0.4195426327248053)

Out[0:8]: np.float64(0.4195426327248053)

In [ ]:
%%px --block
coords = rv.core.CoordinateSpace(
    rv.core.Coordinate(rv.array(np.sort(np.random.rand(10)), chunks=None)),
    rv.core.Coordinate(rv.array(np.sort(np.random.rand(10)), chunks=None)),
    rv.core.Coordinate(rv.array(np.sort(np.random.rand(10)), chunks=None)),)

In [11]:
%%px --block
coords[2].name='sx'
coords[2].unit='ssss'

In [12]:
%%px --block
coords['sx']
coords.get_plot_labels()

Out[0:11]: ('', '', 'sx (ssss)')

Out[1:11]: ('', '', 'sx (ssss)')

Out[3:11]: ('', '', 'sx (ssss)')

Out[2:11]: ('', '', 'sx (ssss)')

In [13]:
%%px --block
coords['sx'].attrs


Out[1:12]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[3:12]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[2:12]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})

Out[0:12]: Attributes({'_ROCKVERSE_DATATYPE': 'Coordinate', 'name': 'sx', 'unit': 'ssss'})