In [1]:
import ipyparallel as ipp

# Create an MPI cluster with 8 engines
cluster = ipp.Cluster(engines="mpi", n=4)

# Start and connect to the cluster
rc = cluster.start_and_connect_sync()

# Enable IPython magics for parallel processing
rc[:].activate()


Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

In [2]:
%%px --block
import rockverse as rv
import numpy as np
self = rv.array(np.random.rand(4,4), chunks=(2,2), overwrite=True, fill_value=0)
self.zarray[...] 


Out[2:1]: 
array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.99240379, 0.29464971, 0.        , 0.        ],
       [0.3664185 , 0.27970719, 0.        , 0.        ]])

Out[3:1]: 
array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.05182745, 0.84302035],
       [0.        , 0.        , 0.12504117, 0.48292434]])

Out[1:1]: 
array([[0.        , 0.        , 0.646852  , 0.09202327],
       [0.        , 0.        , 0.84030251, 0.04507073],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

Out[0:1]: 
array([[0.4544864 , 0.780511  , 0.        , 0.        ],
       [0.34055802, 0.26375878, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [3]:
%%px --block
self[...] 


Out[1:2]: 
array([[0.4544864 , 0.780511  , 0.646852  , 0.09202327],
       [0.34055802, 0.26375878, 0.84030251, 0.04507073],
       [0.99240379, 0.29464971, 0.05182745, 0.84302035],
       [0.3664185 , 0.27970719, 0.12504117, 0.48292434]])

Out[3:2]: 
array([[0.4544864 , 0.780511  , 0.646852  , 0.09202327],
       [0.34055802, 0.26375878, 0.84030251, 0.04507073],
       [0.99240379, 0.29464971, 0.05182745, 0.84302035],
       [0.3664185 , 0.27970719, 0.12504117, 0.48292434]])

Out[0:2]: 
array([[0.4544864 , 0.780511  , 0.646852  , 0.09202327],
       [0.34055802, 0.26375878, 0.84030251, 0.04507073],
       [0.99240379, 0.29464971, 0.05182745, 0.84302035],
       [0.3664185 , 0.27970719, 0.12504117, 0.48292434]])

Out[2:2]: 
array([[0.4544864 , 0.780511  , 0.646852  , 0.09202327],
       [0.34055802, 0.26375878, 0.84030251, 0.04507073],
       [0.99240379, 0.29464971, 0.05182745, 0.84302035],
       [0.3664185 , 0.27970719, 0.12504117, 0.48292434]])