Connected to rockverse-env (Python 3.12.8)

In [2]:
import ipyparallel as ipp
cluster = ipp.Cluster(engines="mpi", n=4)
rc = cluster.start_and_connect_sync()
rc[:].activate()

Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

In [ ]:
%%px --block
import rockverse as rv

import zarr
with zarr.config.set({'array.order': 'F'}):
    z1 = zarr.create_array(shape=(1000,1000,1000), dtype='f8', store=None)
z2 = zarr.create_array(shape=(1000,1000,1000), dtype='f8', store=None)

kwargs=dict(
    shape=(400,400),
    dtype=float,
    store=None,#'/u/gob7/Downloads/test.zarr',
    chunks=8,
    overwrite=True,
    field_name='rod',
    field_unit='s',
    description='rod s xxx',
    voxel_origin=(1, 2, 3),
    voxel_length=(0.1, 0.2, 0.3),
    voxel_unit='mm'
    )

self=rv.voxel_image.zeros(**kwargs)
#self[...] = 3
z1.order, z2.order, self.array.order


[3:execute]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 22
      6 z2 = zarr.create_array(shape=(1000,1000,1000), dtype='f8', store=None)    
      8 kwargs=dict(
      9     shape=(400,400),
     10     dtype=float,
   (...)
     19     voxel_unit='mm'
     20     )
---> 22 self=rv.voxel_image.zeros(**kwargs)
     23 #self[...] = 3
     24 z1.order, z2.order, self.array.order

File ~/rockverse/src/rockverse/voxel_image/__init__.py:221, in zeros(shape, dtype, **kwargs)
    219 kwargs['shape'] = shape
    220 kwargs['dtype'] = dtype
--> 221 kwargs['fill_value'] = 0
    222 return create(**kwargs)

File ~/rockverse/src/rockverse/voxel_image/__init__.py:120, in create(shape, dtype, chunks, store, overwrite, field_name, field_unit, description, voxel_origin, voxel_length, voxel_unit, **kwargs)
    118 elif chunks == 'nprocs':
    119     _chunks = auto_chunk_3d(shap

AlreadyDisplayedError: 4 errors

In [ ]:
%%px --block
self[1:300, 4, :]=88
self._array[...]
#self.math(77, 'set')

[stdout:0] ENTER


[stdout:1] ENTER


[stdout:2] ENTER


[stdout:3] ENTER


Out[3:2]: 
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., 

Out[2:2]: 
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., 

Out[1:2]: 
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., 

Out[0:2]: 
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., 

In [ ]:
%%px --block
self.array.info_complete()

Out[1:3]: 
Type               : Array
Zarr format        : 3
Data type          : DataType.float64
Shape              : (400, 400, 400)
Chunk shape        : (200, 200, 200)
Order              : C
Read-only          : False
Store type         : MemoryStore
Filters            : ()
Serializer         : BytesCodec(endian=<Endian.little: 'little'>)
Compressors        : (ZstdCodec(level=0, checksum=False),)
No. bytes          : 512000000 (488.3M)
No. bytes stored   : 8080
Storage ratio      : 63366.3
Chunks Initialized : 2

Out[0:3]: 
Type               : Array
Zarr format        : 3
Data type          : DataType.float64
Shape              : (400, 400, 400)
Chunk shape        : (200, 200, 200)
Order              : C
Read-only          : False
Store type         : MemoryStore
Filters            : ()
Serializer         : BytesCodec(endian=<Endian.little: 'little'>)
Compressors        : (ZstdCodec(level=0, checksum=False),)
No. bytes          : 512000000 (488.3M)
No. bytes stored   : 11280
Storage ratio      : 45390.1
Chunks Initialized : 2

Out[2:3]: 
Type               : Array
Zarr format        : 3
Data type          : DataType.float64
Shape              : (400, 400, 400)
Chunk shape        : (200, 200, 200)
Order              : C
Read-only          : False
Store type         : MemoryStore
Filters            : ()
Serializer         : BytesCodec(endian=<Endian.little: 'little'>)
Compressors        : (ZstdCodec(level=0, checksum=False),)
No. bytes          : 512000000 (488.3M)
No. bytes stored   : 928
Storage ratio      : 551724.1
Chunks Initialized : 0

Out[3:3]: 
Type               : Array
Zarr format        : 3
Data type          : DataType.float64
Shape              : (400, 400, 400)
Chunk shape        : (200, 200, 200)
Order              : C
Read-only          : False
Store type         : MemoryStore
Filters            : ()
Serializer         : BytesCodec(endian=<Endian.little: 'little'>)
Compressors        : (ZstdCodec(level=0, checksum=False),)
No. bytes          : 512000000 (488.3M)
No. bytes stored   : 928
Storage ratio      : 551724.1
Chunks Initialized : 0

In [6]:
%%px --block

dd= zarr.open('/u/gob7/Downloads/test.zarr')
dd[...]

Out[3:4]: 
array([[[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]]])

Out[2:4]: 
array([[[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]]])

Out[0:4]: 
array([[[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]]])

Out[1:4]: 
array([[[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]],

       [[88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.],
        [88., 88., 88., 88.]]])

In [7]:
%%px --block
import rockverse as rv
xxxa = rv.open('/u/gob7/Downloads/test.zarr')

In [13]:
%%px --block
list(xxxa.array.attrs.keys())

Out[0:11]: 
['_ROCKVERSE_DATATYPE',
 'description',
 'field_name',
 'field_unit',
 'voxel_unit',
 'voxel_origin',
 'voxel_length']

Out[1:11]: 
['_ROCKVERSE_DATATYPE',
 'description',
 'field_name',
 'field_unit',
 'voxel_unit',
 'voxel_origin',
 'voxel_length']

Out[2:11]: 
['_ROCKVERSE_DATATYPE',
 'description',
 'field_name',
 'field_unit',
 'voxel_unit',
 'voxel_origin',
 'voxel_length']

Out[3:11]: 
['_ROCKVERSE_DATATYPE',
 'description',
 'field_name',
 'field_unit',
 'voxel_unit',
 'voxel_origin',
 'voxel_length']