In [1]:
import ipyparallel as ipp

# Create an MPI cluster with 8 engines
cluster = ipp.Cluster(engines="mpi", n=4)

# Start and connect to the cluster
rc = cluster.start_and_connect_sync()

# Enable IPython magics for parallel processing
rc[:].activate()


Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

In [2]:
%%px --block
import rockverse as rv
import numpy as np
self = rv.array(np.random.rand(4,4), chunks=(2,2), overwrite=True, fill_value=0)
self.zarray[:, 0] = 5
self.clean_chunks()
self.zarray[...] 



Out[3:1]: 
array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.72143916, 0.96521001],
       [0.        , 0.        , 0.56059063, 0.58787862]])

Out[1:1]: 
array([[0.        , 0.        , 0.55065349, 0.00528702],
       [0.        , 0.        , 0.65059971, 0.51717228],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

Out[2:1]: 
array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [5.        , 0.62889437, 0.        , 0.        ],
       [5.        , 0.91515989, 0.        , 0.        ]])

Out[0:1]: 
array([[5.        , 0.75809571, 0.        , 0.        ],
       [5.        , 0.92591173, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])