In [1]:
import ipyparallel as ipp

# Create an MPI cluster with 8 engines
cluster = ipp.Cluster(engines="mpi", n=4)

# Start and connect to the cluster
rc = cluster.start_and_connect_sync()

# Enable IPython magics for parallel processing
rc[:].activate()


Starting 4 engines with <class 'ipyparallel.cluster.launcher.MPIEngineSetLauncher'>


  0%|          | 0/4 [00:00<?, ?engine/s]

In [4]:
%%px --block
import rockverse as rv
import numpy as np
self = rv.array(np.random.rand(4,4), chunks=(2,2), overwrite=True, fill_value=0)
self.zarray[...] 


[stdout:0] 0 fill block 0 (0, 0)


[stdout:1] 1 fill block 1 (0, 1)


[stdout:3] 3 fill block 3 (1, 1)


[stdout:2] 2 fill block 2 (1, 0)


Out[0:3]: 
array([[0.25254512, 0.91050838, 0.        , 0.        ],
       [0.00133951, 0.86124624, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

Out[1:3]: 
array([[0.        , 0.        , 0.42972421, 0.34082851],
       [0.        , 0.        , 0.09417459, 0.76300286],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

Out[3:3]: 
array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.81844766, 0.74628807],
       [0.        , 0.        , 0.16028696, 0.42005642]])

Out[2:3]: 
array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.93926178, 0.15889044, 0.        , 0.        ],
       [0.91859736, 0.30083593, 0.        , 0.        ]])

In [5]:
%%px --block
self[...] 


Out[2:4]: 
array([[0.25254512, 0.91050838, 0.42972421, 0.34082851],
       [0.00133951, 0.86124624, 0.09417459, 0.76300286],
       [0.93926178, 0.15889044, 0.81844766, 0.74628807],
       [0.91859736, 0.30083593, 0.16028696, 0.42005642]])

Out[1:4]: 
array([[0.25254512, 0.91050838, 0.42972421, 0.34082851],
       [0.00133951, 0.86124624, 0.09417459, 0.76300286],
       [0.93926178, 0.15889044, 0.81844766, 0.74628807],
       [0.91859736, 0.30083593, 0.16028696, 0.42005642]])

Out[0:4]: 
array([[0.25254512, 0.91050838, 0.42972421, 0.34082851],
       [0.00133951, 0.86124624, 0.09417459, 0.76300286],
       [0.93926178, 0.15889044, 0.81844766, 0.74628807],
       [0.91859736, 0.30083593, 0.16028696, 0.42005642]])

Out[3:4]: 
array([[0.25254512, 0.91050838, 0.42972421, 0.34082851],
       [0.00133951, 0.86124624, 0.09417459, 0.76300286],
       [0.93926178, 0.15889044, 0.81844766, 0.74628807],
       [0.91859736, 0.30083593, 0.16028696, 0.42005642]])

Output for ipengine-1758307878-s5ss-1758307879-21356:
2025-09-19 15:51:21.146 [IPEngine] Loading connection info from $IPP_CONNECTION_INFO
2025-09-19 15:51:21.146 [IPEngine] WARNING | Not using CurveZMQ security
2025-09-19 15:51:21.147 [IPEngine] Loading connection info from $IPP_CONNECTION_INFO
2025-09-19 15:51:21.147 [IPEngine] WARNING | Not using CurveZMQ security
2025-09-19 15:51:21.162 [IPEngine.2] Registering with controller at tcp://127.0.0.1:50025
2025-09-19 15:51:21.162 [IPEngine.1] Registering with controller at tcp://127.0.0.1:50025
2025-09-19 15:51:21.162 [IPEngine.3] Registering with controller at tcp://127.0.0.1:50025
2025-09-19 15:51:21.162 [IPEngine.0] Registering with controller at tcp://127.0.0.1:50025
2025-09-19 15:51:21.167 [IPEngine.2] Requesting id: 2
2025-09-19 15:51:21.167 [IPEngine.1] Requesting id: 1
2025-09-19 15:51:21.167 [IPEngine.3] Requesting id: 3
2025-09-19 15:51:21.167 [IPEngine.0] Requesting id: 0
C:\Users\GOB7\AppData\Local\miniforge3\envs\rockverse\